### ISSUE TITLE
How do I make unauthorized return 401?

### ISSUE THREAD

**Issue by alonstar** [graphql-dotnet/authorization#1]
I can see the error  400 for  "message": "You are not authorized to run this query. Required claim 'role' with any value of 'member' is not present.".

But I need to return 401 http status code, What can I do?

	public class MyType : ObjectGraphType
	{
		public MyType()
		{
			this.AuthorizeWith("AdminPolicy");
			Field<StringGraphType>("name");
		}
	}

**Comment by joemcbride** [comment]
You would need to handle that in your http server.  If you are using the `server` project then this is the code that would need to be changed:

https://github.com/graphql-dotnet/server/blob/a54a95f3807ade7aa4e23cce76fe8e58211053a0/src/AspNetCore/GraphQLHttpMiddleware.cs#L77

At present it just does a 400 error on any error.

**Comment by ntaranov** [comment]
private async Task WriteResponseAsync(HttpContext context, ExecutionResult result)
        {
            var json = _writer.Write(result);

            context.Response.ContentType = "application/json";
            context.Response.StatusCode = result.Errors?.Any() != true
                ? (int)HttpStatusCode.OK
                : result.Errors?.Any(er => (er as ValidationError)?.ErrorCode  == "authorization") == true
                    ? (int)HttpStatusCode.Unauthorized
                    : (int)HttpStatusCode.BadRequest;

            await context.Response.WriteAsync(json);
        }

**Comment by alonstar** [comment]
oh, I got it , thanks.

**Comment by okarlsson** [comment]
If anyone else bumps into this:

I just build a simple if statement that checks for authorization errors in the ExecutionResult like this:

```
if (result.Errors?.Count > 0)
{
        if (result.Errors.Select(e => e.Code).Contains("authorization"))
	{
		var retval = new ErrorResponse()
		{
			MessageForUser = "Unauthorized",
			MessageForDev = GetErrorMessage(result.Errors)
		};
                return new JsonResult(retval)
		{
			StatusCode = 401
		};
	}
	else
	{
		var retval = new ErrorResponse()
		{
			MessageForUser = GetErrorMessage(result.Errors),
			MessageForDev = GetErrorMessage(result.Errors)
		};

		return BadRequest(retval);
	}
}

return Ok(result);
}

private string GetErrorMessage(ExecutionErrors errors)
{
	return string.Join(", ", errors.Select(e => e.Message));
}
```

**Comment by giososa24** [comment]
> I use this code:
> 
>         private async Task WriteResponseAsync(HttpContext context, ExecutionResult result)
>         {
>             var json = _writer.Write(result);
> 
>             context.Response.ContentType = "application/json";
>             context.Response.StatusCode = result.Errors?.Any() != true
>                 ? (int)HttpStatusCode.OK
>                 : result.Errors?.Any(er => (er as ValidationError)?.ErrorCode  == "authorization") == true
>                     ? (int)HttpStatusCode.Unauthorized
>                     : (int)HttpStatusCode.BadRequest;
> 
>             await context.Response.WriteAsync(json);
>         }
> 
> I actually would be happy to see this integrated in the project. 
> 

Hi, I have a question, where do you put this code?
