### ISSUE TITLE
In AuthorizationValidationRule.cs the method CheckAuth is called multiple times. Why?

### ISSUE THREAD

**Issue by ninomllr** [graphql-dotnet/authorization#127]
In one of our projects we need to expand the CheckAuth functionality to check on the database if the user still exists when we send the JWT token. For that purpose we copied the AuthorizationValidationRule.cs and created our own implementation of it and load it in our Startup.cs file.

Now when we add a Console.WriteLine to the CheckAuth method we see that it's called a couple of dozen times. Is this intended? If yes, where would be a good place to implement a check on the database if the user actually exists?

**Comment by joemcbride** [comment]
`AuthorizationValidationRule` is the "framework" code and does not need to be modified.  That rule checks all of the Graph Types in the query to see if they have authorization policies applied to them, which is why `CheckAuth` is called so many times.

You can instead add your own authorization requirements to the framework to extend it.  Create your own `IAuthorizationRequirement` class and add that requirement to your policy.

```csharp
public class UserExistsRequirement : IAuthorizationRequirement
{
    public Task Authorize(AuthorizationContext context)
    {
        // this is the authenticated user
        var user = context.User;

        // check DB here
        return Task.CompletedTask;
    }
}

public static class AuthorizationPolicyBuilderExtensions
{
    public static AuthorizationPolicyBuilder UserExists(this AuthorizationPolicyBuilder builder)
    {
        builder.AddRequirement(new UserExistsRequirement());
        return builder;
    }
}

// build your policy
var authSettings = new AuthorizationSettings();
authSettings.AddPolicy("UserExists", p => p.RequireAuthenticatedUser().UserExists());


// apply the policy to the graph type

/// <summary>
/// CLR type to map to the 'Query' graph type.
/// </summary>
public class Query
{
    /// <summary>
    /// Resolver for 'Query.viewer' field.
    /// </summary>
    [GraphQLAuthorize(Policy = "UserExists")]
    public User Viewer() => new User { Id = Guid.NewGuid().ToString(), Name = "Quinn" };
}
```

**Comment by sungam3r** [comment]
I'll send PR to add this into readme.

**Comment by ninomllr** [comment]
Ok thanks for adding this to the readme!

Reason why we copied AuthorizationValidationRule intially was because we needed to change the error message. We thought it could be a good place to change some things about validation as well. Thanks for clearing this up.

**Comment by sungam3r** [comment]
>  we needed to change the error message

I already do this, will be in v4.
