### ISSUE TITLE
ETA for v4?

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/authorization#129]
Hi, I wanted to update GraphQL to v4 but I encountered some issues that might be related to GraphQL.Authorization.
Here is the [link to the issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/2445).

What would the ETA be for GraphQL.Authorization v4?
Just to know when I can plan to finalize my updates. Are we talking days or weeks?

Thank you!

**Comment by sungam3r** [comment]
Days or weeks: ) One-two weeks. There were many issues in this repository, which would be good to solve in v4. Otherwise, I will have to do the v5 right after the v4 release. I want to include in v4 as more pending features as I can.

**Comment by sungam3r** [comment]
By the way you can use auth package (ASP.NET Core related things) from the server project.

**Comment by cdtlaurence** [comment]
Hey! Is there any update on when v4 will be released? :)

**Comment by sungam3r** [comment]
There is no ETA yet. Too much daily work.

**Comment by Xeviva** [comment]
I am also eagerly awaiting this update. Can we just get this breaking change (broken by GraphQL V4 update) fix out as soon as possible? Personally, I really don't mind if V5 comes quickly after, having this working is far more important to me.

**Comment by sungam3r** [comment]
I'm sorry for the delay. I give an OSS almost all free time, which I have not so much lately. To think about and make all changes, check them and test takes a lot of time. We have several projects on support. It's impossible to manage everything In a limited time. Will have to wait.

**Comment by rmarteleto** [comment]
hi @sungam3r, I am also interested in V4. How can I help to start contributing to this project in general?

**Comment by Shane32** [comment]
The holdup is #128 , I believe, which @sungam3r and @joemcbride were working on.  I'm not sure how you or I can help @rmarteleto .

> There were many issues in this repository, which would be good to solve in v4. Otherwise, I will have to do the v5 right after the v4 release. I want to include in v4 as more pending features as I can.

@sungam3r If you have set aside working on #128, and if the current version compiles and is usable, we should release it, and release v5 if and when #128 is complete.  It is irresponsible of us as maintainers of an OSS project to have projects remain in 'limbo' for an extended time when a version could be released that _would_ work for users.  Please let me know @sungam3r and @joemcbride if you have differing thoughts on this.

Same is also true of the relay project.  If we are not going to work on it, we should release whatever code is there now, considering it has already been updated to the latest version of GraphQL.  (We should review https://github.com/graphql-dotnet/relay/pull/88 first and update the workflow scripts.)  Or mark the entire project as deprecated, if that is the case.  Ref: https://github.com/graphql-dotnet/relay/issues/27

**Comment by Xelit3** [comment]
Hi all

I was having the same [issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/2445) than @julienFlexsoft. 

Let me know if I can help in something related to this release.

**Comment by joemcbride** [comment]
@Shane32 My major concern is that the current refactor removes functionality that users of the framework may depend on, as well as makes it more complicated to use.  You could previously fully evaluate policies outside the context of the GraphQL Rule.  With the refactor that is no longer the case.  So if anyone was relying upon that behavior they would now have to write code that the framework should handle.  There are also a bunch of classes added that make it more complicated to use and seem entirely unnecessary to support V4.  It seems like @sungam3r wants to add a bunch of new features in addition to upgrading to V4.  I think those should be done separately so they can be evaluated separately.  I don't think what is currently there should be shipped.

**Comment by Shane32** [comment]
I understand.  But can we ship it without #128 ?  Or does it need work (one way or another) before another version can be released?  I've not been really following this repo and, not having used this project, have no opinion on its design.  I just think if it's not going to be worked on, it should be released without #128 -- or no?

**Comment by joemcbride** [comment]
@Shane32 It looks like there is another commit on the main branch which has upgrades for V4 that looks like it could go out.  The main CI is breaking on upgrading to v4.2.0, not sure why (looks like a github actions issue vs. a failing test issue).

**Comment by joemcbride** [comment]
@Shane32 Looks like there are a few other changes required, due to having some classes from this library moved to the core library.  Looking at that.

**Comment by joemcbride** [comment]
#148 fixes those issues and should be able to be shipped.  I think we'll just need to remove the `-preview` from the `.csproj` to create an official release.

**Comment by sungam3r** [comment]
All releases are published via [publish](https://github.com/graphql-dotnet/authorization/blob/master/.github/workflows/publish.yml) workflow, no need to remove `-preview`. I will return to work on #128 today. In fact, there are not so many corrections for comments. We will be able to discuss the corrected version and release v4 with or without #128.

**Comment by Shane32** [comment]
> I will return to work on #128 today

Ok then we will hold off on another release for the moment.

**Comment by sungam3r** [comment]
I thought again and let's publish as it is. It is not known how much it still will be delayed.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/authorization/releases/tag/4.0.0
