### ISSUE TITLE
If the policy being used to Authorize is not in defined policy list, it allows anonymous users to bypass it.

### ISSUE THREAD

**Issue by bhushansahni** [graphql-dotnet/authorization#15]
https://github.com/graphql-dotnet/authorization/blob/8ec6cd84854d293f9c250daf79c60dc91a5907d0/src/GraphQL.Authorization/AuthorizationEvaluator.cs#L38

Can we add a check to validate it?
            if (authPolicies.Count == 0)
            {
                return AuthorizationResult.Fail(new List<string>() { "Unauthorized! " }); //Or some relevant message?
            }

**Comment by sungam3r** [comment]
@bhushansahni @joemcbride I think this issue has been resolved.
