### ISSUE TITLE
ClaimsPrincipal not retrived trying to use AuthorizeWith in GraphQL queries

### ISSUE THREAD

**Issue by Xelit3** [graphql-dotnet/authorization#152]
Hi all,

I am trying to follow the [example ](https://github.com/graphql-dotnet/authorization/tree/master/src/Harness) provided for an authorization mechanism in a GraphQL query. The project is using JWT like default schema, and I tested with a REST test controller and the ClaimsIdentity is well managed.

However, in the GprahQL schemas I am always retrieving that the user is not containing the requested rule.

Let me paste the relevant code:

**Startup ConfigureServices:**
```csharp
[...]
               .AddSingleton<IAuthorizationEvaluator, AuthorizationEvaluator>()
               .AddTransient<IValidationRule, AuthorizationValidationRule>()
               .AddTransient(s =>
               {
                   var authSettings = new GraphQL.Authorization.AuthorizationSettings();
                   authSettings.AddPolicy("AdminPolicy", p => p.RequireClaim("role", "Admin"));

                   return authSettings;
               })
               .AddGraphQL(options =>
               {
                   options.EnableMetrics = true;
               })
               .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true)
               .AddSystemTextJson()
               .AddDataLoader()
               .AddUserContextBuilder(context => new GraphQLUserContext { User = context.User })
               .AddGraphTypes(typeof(ApplicationSchema), ServiceLifetime.Scoped)
               .AddGraphTypes(typeof(UserSchema), ServiceLifetime.Scoped);
[...]
```

**Startup Configure:**
```csharp
[...]
            app.UseGraphQL<UserSchema>("/api/users");
            app.UseGraphQL<ApplicationSchema>("/api/applications");

            app.UseGraphQLPlayground(new PlaygroundOptions { GraphQLEndPoint = "/api/users" }, "/ui/users");
            app.UseGraphQLPlayground(new PlaygroundOptions { GraphQLEndPoint = "/api/applications" }, "/ui/applications");
[...]
```

**Query tested:**
```csharp

public class UserQuery : GraphQueryBase<UserDbModel>
    {
        public UserQuery(IUnitOfWork unitOfWork)
            : base(unitOfWork)
        {

            Field<ListGraphType<UserModel>>(
                "all",
                resolve: context => _modelRepository.FromAll().ToList()                
                )
                .AuthorizeWith("AdminPolicy")
                ;
        }
    }

```

If I have a check on the JWT payload sent to the API, I see the following:

```json
{
   "sub":"9fe2bea3-4783-4fd1-25ba-08d8e17555a3"
   "unique_name":"TestUser"
   "email":"test.user@mail.com"
   "role":"Admin"
   "nbf":1620143858
   "exp":1620147458
   "iat":1620143858
   "iss":"TestApp"
   "aud":"TestApp"
}
```

As you can see, the role is there, however trying to check the user retrived by the HttpContext at startup level I can see the following:

![image](https://user-images.githubusercontent.com/55638917/117142206-b99eb480-adaf-11eb-8859-77c13dc105af.png)

so:
![image](https://user-images.githubusercontent.com/55638917/117142037-8cea9d00-adaf-11eb-8e08-61bfe769bfde.png)

So giving that, the UI is at the end receiving the following:

> "GraphQL.Validation.ValidationError: You are not authorized to run this query. Required claim 'role' with any value of 'Admin' is not present."

Would you know what is missing here? or where is the issue?

Thanks a lot in advance

**Comment by joemcbride** [comment]
1) This is probably because ASP.NET is not trying to authenticate the JWT before hitting the GraphQL endpoint/middleware. Does your API always require authentication, or are some queries allowed for anonymous users?

2) Do you have Authentication wired up in services for JWT?

```csharp
services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme);
```

```
app.UseAuthentication();
```

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio#configure-identity-services
https://www.tektutorialshub.com/asp-net-core/authentication-in-asp-net-core/

3) It looks like you're using the GraphQL Server project which uses Middleware.  If some endpoints do not require authentication, then you will probably have to write your own middleware to run before the GraphQL middleware to "challenge" the token if it exists.

```csharp
// looking up on what class you call this exactly
ChallengeAsync(JwtBearerDefaults.AuthenticationScheme);
```

https://www.tektutorialshub.com/asp-net-core/authentication-in-asp-net-core/

4) Make sure your `GraphQLUserContext` implement the `IProvideClaimsPrincipal` interface.

**Comment by Xelit3** [comment]
Hi @joemcbride !!

Thanks a lot for your quick reply

In relation to point 1: All endopoints will require authentication, so I can imagine that it would be better to protect the whole schema right? By the moment I was only testing with one query.

Then, regarding point 2 and 4 are ok currently.

I will take a look to point 3, because it is true, my project is currently using the Middleware from GraphQL server.

Thanks a lot, I will revert once I'm able to tackle again

**Comment by Xelit3** [comment]
Hi @joemcbride !!

I have checked your points, but is still not working, let me five some additional info point by point:

1. As commented, at the end all will require auth, so I checked using AuthorizeWith both in some queries and at first. In both I have same result, not retrieving Identity info:

```csharp
            this.AuthorizeWith("AdminPolicy");

            Field<ListGraphType<UserModel>>(
                    "all", resolve: context => _modelRepository.FromAll().ToList()
                );
```

2. Yes, but not in the same way, however I checked with a REST controller and the token is properly retrieved from the same UI and the claims and roles are there.

```csharp
   {
            services.AddAuthentication(opt =>
                {
                    opt.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    opt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                    opt.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(opt =>
                {
                    opt.SaveToken = true;
                    opt.RequireHttpsMetadata = true;
                    opt.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuer = true,
                        ValidateAudience = true,
                        ValidateLifetime = true,
                        ValidateIssuerSigningKey = true,
                        ValidAudience = authSettings.SiteName,
                        ValidIssuer = authSettings.SiteName,
                        IssuerSigningKey = SecurityKeyHelper.GetSecurityKey(privateKey)
                    };
                });
                
              services
                .AddAuthorization(x => x.DefaultPolicy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
                    .Build());
```

3. Yes indeed. I checked your proposal and the link provided, but I'm not sure if something else is missing or I'm not understading something... this is the code as written now:

```csharp
 if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();

                app.UseSwagger();
                app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("/swagger/v1/swagger.json", "ChustaSoft Profiler V1");
                    c.RoutePrefix = string.Empty;
                });

                app.UseHsts();
                app.UseHttpsRedirection();
            }

            app.UseRouting();
            app.UseCors(CORS_POLICY_NAME);

            app.Use(async (context, next) =>
            {
                await context.ChallengeAsync(JwtBearerDefaults.AuthenticationScheme);
                await next.Invoke();
            });
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });


            app.UseGraphQL<UserSchema>("/api/users");
            app.UseGraphQL<ApplicationSchema>("/api/applications");

            app.UseGraphQLPlayground(new PlaygroundOptions { GraphQLEndPoint = "/api/users" }, "/ui/users");
            app.UseGraphQLPlayground(new PlaygroundOptions { GraphQLEndPoint = "/api/applications" }, "/ui/applications");
```

4. Yes it is:
```csharp
    public class GraphQLUserContext : Dictionary<string, object>, IProvideClaimsPrincipal
    {
        private ClaimsPrincipal user;

        /// <inheritdoc />
        public ClaimsPrincipal User { get => user; set => user = value; }
    }
```

Do you have an idea of what else is missing or not working properly?

Many many thanks in advance :)

**Comment by ViRuSTriNiTy** [comment]
I was struggling with an empty ClaimsPrinicipal for the last 8 hours also. I think what is missing is this:

```
services.AddGraphQLAuthorization(options =>
{
    options.AddPolicy(YourPolicyName, p =>
    {
        // use authentication schemes configured in Startup.cs
        p.AddAuthenticationSchemes(options.DefaultPolicy.AuthenticationSchemes.ToArray());

        p.RequireAuthenticatedUser();
    });
})

app.UseEndpoints(endpoints =>
{
	endpoints.MapGraphQL<YourSchema>().RequireAuthorization(YourPolicyName);
});
```

Hope this helps.

**Comment by sungam3r** [comment]
@Xelit3 Did you solve this problem? Maybe you mixed APIs from different ptojects? We have this one for general-purpose auth and [another](https://github.com/graphql-dotnet/server/tree/master/src/Authorization.AspNetCore) one for ASP.NET Core.

**Comment by sungam3r** [comment]
Reopen if you have any questions.
