### ISSUE TITLE
How to get a status code 401 when not authorized

### ISSUE THREAD

**Issue by john-roland** [graphql-dotnet/authorization#166]
Hi,

Is there's a way to get a 401 status code instead of a 200 + the graphql message (when the authentication is not ok) ?
I'm trying to have this in order to have an easiest way to renew jwt tokens

maybe by implementing a IValidationRule ?

thanks,

**Comment by ntaranov** [comment]
@john-roland, you might be interested in reading this for extra background

https://github.com/graphql-dotnet/server/issues/159

**Comment by Shane32** [comment]
I wrote my own ASP.NET middleware to process GraphQL requests, and one of the things it does is validate the JWT token passed in and return a 401 response code if it is invalid - prior to calling the document executer (which does validation).  Sorry, not sure how that answer helps if you're using this authorization library.

**Comment by ntaranov** [comment]
@Shane32 , I wrote a custom middleware piggybacking everything, the magic sauce is here
```csharp
        private Task WriteResponseAsync(HttpContext context, IDocumentWriter writer, ExecutionResult result, int statusCode = 200)
        {
            var json = writer.Write(result);

            statusCode = result.Errors?.Any() != true
                ? (int)HttpStatusCode.OK
                : result.Errors?.Any(er => (er as ValidationError)?.Code == "authorization") == true
                    ? (int)HttpStatusCode.Unauthorized
                    : (int)HttpStatusCode.BadRequest;

            result.Errors?.ToList().ForEach(e => _logger.LogError($"GraphQL execution error: {e}"));

            context.Response.ContentType = "application/json";
            context.Response.StatusCode = statusCode; // OK

            return context.Response.WriteAsync(json);
        }
```

**Comment by sungam3r** [comment]
> Is there's a way to get a 401 status code instead of a 200 + the graphql message (when the authentication is not ok) ?

Of course. Authorize user before handling graphql request. 401/200/xxx - these all are HTTP transport codes. GraphQL as it is has nothing to do with HTTP transport layer.

**Comment by sungam3r** [comment]
Closed due lack of feedback.

**Comment by john-roland** [comment]
sorry for being silent, thank you all for your answers, I've done a bit like you've said, interrupting the request before the graphql processing
