### ISSUE TITLE
Move GraphQLAuthExtensions from Harness into new package

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/authorization#185]
In GraphQL.NET we have 
![изображение](https://user-images.githubusercontent.com/21261007/145726309-63c265d3-13e8-43b5-b318-0b6de9cfa847.png)
I propose to do the same here - add package `GraphQL.Authorization.MicrosoftDI`. I remember that I saw a few issues, where people did not understand how to plug-in authorization in theirs apps. They were confused. They were advised to simply copy the code from Harness. Not good. ping @Shane32

**Comment by sungam3r** [comment]
If OK, I want to add this feature in v5.

**Comment by Shane32** [comment]
I looked at the two methods within `GraphQLAuthExtensions.cs` file under Harness.  It seems to me that they only need access to `GraphQL.DI.IGraphQLBuilder` as there is no MS-DI or ASP.Net-specific methods contained in there.  These methods should be added to the current version of GraphQL.Authorization, without waiting for v5, as `GraphQL.DI.IGraphQLBuilder` was included in GraphQL.NET 4.6.  I would not create another nuget package.

**Comment by sungam3r** [comment]
`GraphQL.DI.IGraphQLBuilder` 🤔  ? Is this a new project? I have not seen yet, 500 emails :(.

**Comment by Shane32** [comment]
See https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#dependency-injection-registration-helpers

Added and revised in:
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2571
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2607
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2612

**Comment by Shane32** [comment]
Basically, it allows 3rd party libraries such as GraphQL.Authorization to do the following all within a single `IGraphQLBuilder` method:

- Register services within the user's DI framework (any DI framework, and without a dependency)
- Configure options using the options configuration pattern (without a dependency on the MS options pattern)
- Configure schema options
- Configure execution options

In this case, the new `AddAuthorization` method does 3 of the 4 listed above:
- Configures authorization options based on the provided delegate
- Registers necessary classes within the DI framework
- Adds the authorization validation rule during execution

**Comment by Shane32** [comment]
@sungam3r Check out this sample which uses the new `IGraphQLBuilder` approach:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Harness/Startup.cs#L30..L51
