### ISSUE TITLE
Not working with GraphQL package >=2.2

### ISSUE THREAD

**Issue by leddt** [graphql-dotnet/authorization#21]
When updating to the latest version of the GraphQL package (2.3.0 at the time of raising this issue), I get an exception when calling `.AuthorizeWith("my-policy")` :

> MissingMethodException: Method not found: 'Void GraphQL.EnumerableExtensions.Fill(System.Collections.Generic.IList`1<!!0>, !!0)'.

This seems to be because the GraphQL package removed the `EnumerableExtensions.Fill` method in version 2.2.

**Comment by joemcbride** [comment]
Pushed 2.0.27 to NuGet.org with the fix

**Comment by RehanSaeed** [comment]
I guess we need to make the same change in the server auth project.
