### ISSUE TITLE
EnumerableExtensions

### ISSUE THREAD

**Issue by mohsin31** [graphql-dotnet/authorization#23]
Please help
EnumerableExtensions class in present in 2.0 but not available in 2.3.
 What is alternate for  =>  ist.Fill(policy); 
 public static void AuthorizeWith(this IProvideMetadata type, string policy)
        {
            var list = GetPolicies(type);
            list.Fill(policy); // Available in 2.0 but not in 2.3
            type.Metadata[PolicyKey] = list;
        }

**Comment by joemcbride** [comment]
This is fixed in version `2.0.27` of `GraphQL.Authorization`.  See #21

**Comment by mohsin31** [comment]
Thanks it is working.
