### ISSUE TITLE
Access User's Claims from Inside a Mutation?

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/authorization#24]
Hello guys!
I am trying to use JWT authentication and now I need to get some info out of my token from inside my mutation. I can use IHttpContextAccesor, get the token from the request header and manually take out what I need. This is kinda not cool so is there a way to access the user's claims from a mutation?

My mutation code:
```
private async Task<MyModel> Resolve(ResolveFieldContext<object> context)
{
    context.UserContext.Claims ???
}
```

That UserContext seems empty.

I tried generating my token in 2 ways:

1st way:
```
public string CreateUserToken(User user, Guid companyId)
        {
            DateTime nowUtc = DateTime.UtcNow;
            DateTime expires = nowUtc.AddMinutes(_options.UserTokenLifetime);
            DateTime centuryBegin = new DateTime(1970, 1, 1).ToUniversalTime();
            long exp = (long)(new TimeSpan(expires.Ticks - centuryBegin.Ticks).TotalSeconds);
            long now = (long)(new TimeSpan(nowUtc.Ticks - centuryBegin.Ticks).TotalSeconds);

            var payload = new JwtPayload
            {
                { "sub", user.Id },
                { "iss", _options.Issuer },
                { "iat", now },
                { "exp", exp },
                { "company", companyId },
                { "roles", JsonConvert.SerializeObject(user.GetRolesByCompanyId(companyId)) }
            };
            
            return _jwtSecurityTokenHandler.WriteToken(new JwtSecurityToken(_jwtHeader, payload));
        }
```

2nd way:
```
public string CreateUserToken(User user, Guid companyId)
        {
           var claims = new List<Claim>
            {
                new Claim("user", user.Id.ToString()),
                new Claim("company", companyId.ToString())
            };

            foreach (var role in user.GetRolesByCompanyId(companyId))
            {
                claims.Add(new Claim(ClaimTypes.Role, role));
            }
            
            var tokenDescriptor = new SecurityTokenDescriptor
            {  
                Subject = new ClaimsIdentity(claims),
                Expires = DateTime.Now.AddMinutes(Convert.ToInt32(_options.UserTokenLifetime)),  
                Issuer = _options.Issuer ,
                IssuedAt = DateTime.Now            
            };
            
            return _jwtSecurityTokenHandler.WriteToken(_jwtSecurityTokenHandler.CreateToken(tokenDescriptor));
        }
```

I followed this example project [https://github.com/graphql-dotnet/authorization/issues/10](url) on how to enable authorization.

At this point I don't care about policies and permissions, I just need that "comapnyId" out of my token. I would be grateful if someone could help. Thanks in advance!

**Comment by joemcbride** [comment]
You should have some code that looks something like the following, to populate the User on your `UserContext` class.

```csharp
    var settings = new GraphQLSettings
    {
        BuildUserContext = ctx =>
        {
            var userContext = new GraphQLUserContext
            {
                User = ctx.User // <--- this populates the User on your UserContext class from HttpContext
            };

            return Task.FromResult(userContext);
        }
    };

public class GraphQLUserContext : IProvideClaimsPrincipal
{
    public ClaimsPrincipal User { get; set; }
}

public class GraphQLSettings
{
    public Func<HttpContext, Task<object>> BuildUserContext { get; set; }
}
```

How are you building and passing your `UserContext` to the GraphQL Engine?

**Comment by kmanev073** [comment]
> You should have some code that looks something like the following, to populate the User on your `UserContext` class.
> 
> ```cs
>     var settings = new GraphQLSettings
>     {
>         BuildUserContext = ctx =>
>         {
>             var userContext = new GraphQLUserContext
>             {
>                 User = ctx.User // <--- this populates the User on your UserContext class from HttpContext
>             };
> 
>             return Task.FromResult(userContext);
>         }
>     };
> 
> public class GraphQLUserContext : IProvideClaimsPrincipal
> {
>     public ClaimsPrincipal User { get; set; }
> }
> 
> public class GraphQLSettings
> {
>     public Func<HttpContext, Task<object>> BuildUserContext { get; set; }
> }
> ```
> 
> How are you building and passing your `UserContext` to the GraphQL Engine?

I was looking at this example: [https://github.com/graphql-dotnet/authorization/blob/master/src/Harness/Startup.cs](url)

**Comment by joemcbride** [comment]
If you’re using that example then it should be working...

**Comment by kmanev073** [comment]
> If you’re using that example then it should be working...

Yeah, you are right. It works. My context is really set to my own GraphQLUserContext. However I can't access the claims that are in my token. Probably I'm not generating my token correctly. Is there any example I can check? Thanks in advance!

**Comment by kmanev073** [comment]
Anyone?
