### ISSUE TITLE
Creating JWT with Role Claims

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/authorization#26]
Hello!

I was searching for examples but couldn't find anything that shows how to create a JWT token that can hold the user's roles. I see some examples like this:
`authSettings.AddPolicy("AdminPolicy", _ => _.RequireClaim("role", "Admin"))`
Anyway I can't understand how to add that claim into my JWT token. Before I started using GraphQL I was generationg my JWTs with this code:
```
public string CreateUserToken(User user, Guid companyId)
        {
            DateTime nowUtc = DateTime.UtcNow;
            DateTime expires = nowUtc.AddMinutes(_options.UserTokenLifetime);
            DateTime centuryBegin = new DateTime(1970, 1, 1).ToUniversalTime();
            long exp = (long)(new TimeSpan(expires.Ticks - centuryBegin.Ticks).TotalSeconds);
            long now = (long)(new TimeSpan(nowUtc.Ticks - centuryBegin.Ticks).TotalSeconds);

            var payload = new JwtPayload
            {
                { "sub", user.Id },
                { "iss", _options.Issuer },
                { "iat", now },
                { "exp", exp },
                { "company", companyId },
                { "roles", JsonConvert.SerializeObject(user.GetRolesByCompanyId(companyId)) }
            };
            
            return _jwtSecurityTokenHandler.WriteToken(new JwtSecurityToken(_jwtHeader, payload));
        }
```
The roles array was automatically recognized by dotnet core and I was able to use the authorization attributes on my controllers. However in graphql this is not supported or I am making a mistake.

I would be grateful if anyone could help me resolve the issue.

**Comment by joemcbride** [comment]
```
{ "roles", JsonConvert.SerializeObject(user.GetRolesByCompanyId(companyId)) }
```

My understanding is that would create a `roles` claim with multiple values, assuming that serializes to an array.  The example uses a singular `role` claim.

Did you try matching the name of the claim to your `roles`?  At a minimum, the name of the claims have to match.

**Comment by kmanev073** [comment]
> ```
> { "roles", JsonConvert.SerializeObject(user.GetRolesByCompanyId(companyId)) }
> ```
> My understanding is that would create a `roles` claim with multiple values, assuming that serializes to an array. The example uses a singular `role` claim.
> 
> Did you try matching the name of the claim to your `roles`? At a minimum, the name of the claims have to match.

Yeah this just creates an array of strings (the role names) and places it inside the token. I should be able access my token claims with `context.UserContext.Claims ` from inside a mutation for example, however my roles aren't there.

**Comment by joemcbride** [comment]
Is it populated at all?  Is _any_ of the information there?

**Comment by kmanev073** [comment]
> Is it populated at all? Is _any_ of the information there?

Here is a screenshot of my context: [https://i.imgur.com/lp6Noch.png](url)
And here's how my JWT looks:
```
{
  "sub": "3ced78d7-f611-4099-95e0-59e49279cf92",
  "iss": "System",
  "iat": 1542147174,
  "exp": 1542190374,
  "company": "8c7a1275-ba67-47a2-ad8f-d452416b98e9",
  "roles": "[\"Administrator\"]"
}
```

**Comment by joemcbride** [comment]
If you look at that screenshot the `Identity.IsAuthenticated` is false.  That means the `ClaimsPrincipal` is not getting populated.  How have you configured your `JwtBearer` authentication?  Is it set to be enabled by default?

You're passing that in a http `Authorization` header?  You should see the ASP.NET Core JwtBearer middleware handling the request in logs.

```
Authorization Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkY0NTI2Qj...
```

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
  .AddJwtBearer(cfg =>
  {
    cfg.TokenValidationParameters = new TokenValidationParameters()
    {
      ValidateIssuer = true,
      ValidIssuer = _config["Security:Tokens:Issuer"],
      ValidateAudience = true,
      ValidAudience = _config["Security:Tokens:Audience"],
      ValidateIssuerSigningKey = true,
      IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config["Security:Tokens:Key"])),
 
    };
  });
```

**Comment by kmanev073** [comment]
It worked! I had missed: `app.UseAuthentication();` and I was passing the Authorization header wrongly. Thank you!

**Comment by BKB503** [comment]
@kmanev073  I'm getting same thing, I have added app.UseAuthentication(); didn't work, When I add 
var result1 = await httpContext.AuthenticateAsync("Bearer"); in Validation rule then setting the prinicpal to current http context. then claims got populated

I'm not sure what is the best solution and I need it part of ValidationRule or some where global in The GraphQL middlware any help really appreciated
