### ISSUE TITLE
Compatibility with GraphQL .NET 8.x

### ISSUE THREAD

**Issue by irvanherz** [graphql-dotnet/authorization#294]
Hello,

I noticed that the latest release of graphql-dotnet/authorization is not yet compatible with GraphQL .NET 8.x. Since GraphQL .NET v8 has been released recently, it would be great to have an update or guidance on when a compatible version of graphql-dotnet/authorization will be available.

Is there a planned timeline for this update, or any recommended workarounds in the meantime?

Thank you for all your hard work on this project!

**Comment by Shane32** [comment]
8.0 compatible version released.  Please keep in mind that we only recommend and maintain the authorization rule located in the GraphQL.Server.Transports.AspNetCore project.
