### ISSUE TITLE
question - Authorize only without policy

### ISSUE THREAD

**Issue by stephenlautier** [graphql-dotnet/authorization#296]
How to get `this.Authorize()` to work?

Following your samples managed to get `this.AuthorizeWithPolicy("default")`  to work however the basic one i cannot get it to work, and i cannot find any `DefaultPolicy` similar to ASPNET

e.g.

```cs
options.DefaultPolicy = new AuthorizationPolicyBuilder()
	.AddAuthenticationSchemes()
	.RequireAuthenticatedUser()
	.RequireClaim("scope", "XXX")
	.Build()
```

Some of my code highlighting some key points
```cs
// configure GQL Auth
.AddAuthorization(settings =>
{
	settings.AddPolicy("default", policy => policy.RequireAuthenticatedUser());
})

// setting user
.ExecuteAsync(opts =>
    opts.User = User;

// graph type
this.AuthorizeWithPolicy("default"); // works
this.Authorize(); // doesnt work
```

**Comment by Shane32** [comment]
This package has not been updated with functionality for Authorize, AuthorizeWithRoles and AllowAnonymous.  See [v5 migration guide](https://graphql-dotnet.github.io/docs/migrations/migration5/#20-code-classlanguage-textauthorizecode-code-classlanguage-textauthorizewithrolescode-and-code-classlanguage-textallowanonymouscode-extension-methods-added-in-graphql-510-and-511).  Please use the authorization rule in the [GraphQL.NET Server repo](https://github.com/graphql-dotnet/server?tab=readme-ov-file#authorization-configuration) instead, and remove the reference to this nuget package.

**Comment by Shane32** [comment]
Following the link to the server repo's instructions, you will find transport-level authorization configuration settings, which restricts access to the endpoint, similar to an ASP.NET Core default policy.  Instructions are also included if you want to allow access to introspection requests or a portion of your schema via `AllowAnonymous`.

**Comment by stephenlautier** [comment]
Thank you for your response!
