### ISSUE TITLE
Authorization depending on property value of returned object

### ISSUE THREAD

**Issue by micmartin** [graphql-dotnet/authorization#31]
First of all thank you so much for your great work. It's really fun using GraphQL!

Is there on option to authorize an object depending on a property value after getting the object from a databasebase? 
In my special case I need to do authorization depending on a resource ownership. The user is allowed to query for objects of a specific type, but only if he is the owner of the resource.
I already played with the leave action of the INodeVisitor "Validate" method, but the AuthorizationContext in IAuthorizationRequirement.Authorize does not provide any Information about the resource.
Am I missing something here?

**Comment by joemcbride** [comment]
No, you’re not missing anything.  These authorization checks utilize the existing GraphQL validation, which runs before the query is executed.  If you need to access a value that is first resolved/fetched in a field, then you will have to do that manually yourself.

**Comment by hanlindev** [comment]
Hi @micmartin @joemcbride, please allow me to do a shameless plugin here. Having worked with a pretty sophisticated privacy system at work, I wanted to achieve something similar using this library. But I discovered it couldn't be done so I quickly spawned my own take on GraphQL authorization - https://github.com/hanlindev/graphql-privacy .

@micmartin what you described is one of the first use cases I wanted to handle so I think my library should be able to solve your problem. However it was just created a couple of weeks ago. The implementation is a bit hacky and there can be many bugs laying around. Anyways you could still look at my code and create your own version if you desire.

**Comment by sungam3r** [comment]
@micmartin Is this issue still actual?

**Comment by micmartin** [comment]
I soved that problem by doing an authorization check on the "main" entites while retrieving them. No a nice and general solution but it works for my needs.
@hanlindev sorry for not responding to your comment, must have missed the notification

**Comment by sungam3r** [comment]
As @joemcbride said
>  These authorization checks utilize the existing GraphQL validation, which runs **before** the query is executed.  If you need to access a value that is first resolved/fetched in a field, then you will have to do that manually yourself.

Closing this issue as `wontfix`.
