### ISSUE TITLE
How to authorize request for an API-KEY ?

### ISSUE THREAD

**Issue by ashishkapur1** [graphql-dotnet/authorization#34]
Hello there

How can i authorize both my graph input types and graph object types to only proceed if the request header contains specific header key?

Could you please provide example.

Thank you

Ashish

**Comment by sungam3r** [comment]
Authorization requirement works with `AuthorizationContext`. I think the main focus was on `AuthorizationContext.User` and not on custom headers. But you can use `AuthorizationContext.UserContext` for this - first store api key in it and then check it in your custom authorization requirement.

**Comment by sungam3r** [comment]
Closed as answerred and due to lack of feedback.
