### ISSUE TITLE
Require Authorization Without Checking Roles

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/authorization#35]
Hello!

I see that I can define auth policies like this:
```authSettings.AddPolicy("AdministratorPolicy", _ => _.RequireClaim(ClaimTypes.Role, "Administrator"));```
Then I could use this like:
```
public class MyType : ObjectGraphType
{
    public MyType()
    {
        this.AuthorizeWith("AdministratorPolicy");
        Field<StringGraphType>("name").AuthorizeWith("SomePolicy");
    }
}
```

So far so good, but I have parts in my app that require the user to be authenticated but do not require a specific role. Is there anyway I could define a policy that just checks if the user is authorized without specifying required roles?

Something like the [Authorize] attribute in the controllers.

Thanks in advance!

**Comment by BKB503** [comment]
@ganhammar I'm in same situation how to check user identity is authenticated ?  before adding authorization on graphtype 

If I add below in valdation rule and setting back to context is working, is there any other way to check request is authenticated?
  var httpContext = _httpContextAccessor.HttpContext;
            var result1 = await httpContext.AuthenticateAsync("Bearer");
            _httpContextAccessor.HttpContext.User = result1.Principal;

**Comment by OpenSpacesAndPlaces** [comment]
See https://github.com/graphql-dotnet/authorization/issues/49#issuecomment-512007347 for a slightly longer example, but as @ganhammar showed, IAuthorizationRequirement is likely what you'd be looking for.

**Comment by sungam3r** [comment]
@kmanev073 This issue has already been resolved. Now you can use [this requirement](https://github.com/graphql-dotnet/authorization/blob/master/src/GraphQL.Authorization/AuthenticatedUserRequirement.cs) and [that builder method](https://github.com/graphql-dotnet/authorization/blob/master/src/GraphQL.Authorization/AuthorizationPolicyBuilder.cs#L42).

**Comment by sungam3r** [comment]
Closed as resolved.
