### ISSUE TITLE
Authorization Not Respected when returning ListGraphType of Authorized Type

### ISSUE THREAD

**Issue by aaronjedwards** [graphql-dotnet/authorization#36]
For context I have written my own `IAuthorizationRequirement`. In my case, I have a type that is registered in my schema (`MyType`) protected with `this.AuthorizeWith("MyRegisteredPolicyName")` and authorization is working as expected for a query similar to below:

```c#
Field<MyType>(
        "myType",
        arguments: new QueryArguments(new QueryArgument<StringGraphType> { Name = "id" }),
        resolve: context =>
        {
          var id = context.GetArgument<string>("id");
          var obj = db.Find(id);
          return obj;
        });
```

However, when the Query resolves to a list of the same type (`ListGraphType<MyType>`)
```c#
Field<ListGraphType<MyType>>(
        "myTypes",
        resolve: context =>
        {
          var list = db.All();
          return list;
        });
```
The authorization requirement is not enforced. I was expecting that whenever the type was accessed (directly or indirectly), that the authorization requirements would be enforced. Is this by design?

**Comment by joemcbride** [comment]
I would expect that to fail.  I think I know what the issue is:

https://github.com/graphql-dotnet/authorization/blob/0b598fa37a9ba31bb43af26a938cf389117b2a4f/src/GraphQL.Authorization/AuthorizationValidationRule.cs#L57

`fieldDef.ResolvedType` should be getting the "root" GraphType here instead of just passing `ResovledType`, since that `ResolvedType` could be a `NonNullGraphType<T>` or `ListGraphType<T>`.

**Comment by aaronjedwards** [comment]
I was able to work around it for now by adding `AuthorizeWith(...)` to the field of the query directly. Would you consider this a fairly simple bug to fix? If so, I can take a crack at it.

**Comment by joemcbride** [comment]
@aaronjedwards It was fairly simple - pushed up #37 to fix it.

**Comment by aaronjedwards** [comment]
@joemcbride Awesome! Thanks for the quick turn around! I ask only because I don't have any insight into the matter, but how quickly can a simple bug fix like this get pushed through to the nuget package?

**Comment by joemcbride** [comment]
Once the build completes on the master branch I can push the nuget package to nuget.org.  After I push it there it usually takes 10-15 minutes for nuget.org to index it.

**Comment by joemcbride** [comment]
And ... I just remembered I didn't bump the version. So doing that and running another master build.

**Comment by joemcbride** [comment]
Its published, just need to wait for indexing.

https://www.nuget.org/packages/GraphQL.Authorization/2.1.29

**Comment by aaronjedwards** [comment]
@joemcbride Thanks again for the quick response. Ive got the latest package and it is working as intended!
