### ISSUE TITLE
Feature Request: HttpContext

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/authorization#39]
I'm working in .Net Framework without Identity.

I'm calling "HttpContext.Current" from my "IAuthorizationRequirement" class, which works, but is a bad practice/pattern to follow.

The request would be to include in HttpContext "(AuthorizationContext context)" passed down through from the originally Web API context.

**Comment by OpenSpacesAndPlaces** [comment]
As a follow-up - I ended up used "_.UserContext" to pass "HttpContext".

**Comment by joemcbride** [comment]
That would be the suggested way to solve it. This solution is transport independent, so it won't ever have a direct reference to `HttpContext`.
