### ISSUE TITLE
Feature Request: Error Access

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/authorization#40]
In the current version only "ReportError" from "AuthorizationContext context" is available,

Having a pass-up for "rfc.Errors.Add(new ExecutionError" like you can from Resolvers would be helpful.
Particularly I'm looking at wanting to use the optional pass-in "new Dictionary<String, Object>()".

**Comment by sungam3r** [comment]
Sorry, I do not understand what you want. Сan you please explain in more detail?

**Comment by sungam3r** [comment]
Closed due to inactivity.
