### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by jalchr** [graphql-dotnet/authorization#48]
Are there any plans for releasing on a regular basis?
When can we expect a new release ?

**Comment by joemcbride** [comment]
Hey, I've published `3.0.35-preview-35` to NuGet.org which updates the project to the preview of the `GraphQL` project.  There isn't a whole lot of churn in this project so there aren't a lot of releases.  What specifically are you looking for?

**Comment by sungam3r** [comment]
@jalchr https://www.nuget.org/packages/GraphQL.Authorization/3.0.38-preview-38

**Comment by sungam3r** [comment]
Closed due to inactivity.
