### ISSUE TITLE
In multi-query documents, trigger authorization rules on targeted queries only

### ISSUE THREAD

**Issue by ProudOne** [graphql-dotnet/authorization#5]
Currently, if being invoked on an input document with multiple named queries, auth validation walks the entire document. This leads to the request being rejected if any of the queries in the document fail authorization even if the failing queries are not requested.

The entire document will be traversed here: [Line 59 in DocumentValidator.cs](https://github.com/graphql-dotnet/graphql-dotnet/blob/2775a9ab16934cc744fd94b9fc75d6e21134f03e/src/GraphQL/Validation/DocumentValidator.cs#L59)
This should be changed to only walk the selected query.

**Comment by sungam3r** [comment]
Will be released in v5.
