### ISSUE TITLE
Using dependency injection in AuthorizationRequirement

### ISSUE THREAD

**Issue by joacoleza** [graphql-dotnet/authorization#54]
Hi, as I need one registered service to evaluate the authorization, is there a way to use Dependency Injection when implementing `IAuthorizationRequirement` ?

I want to achieve something similar to [handlers](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/dependencyinjection?view=aspnetcore-2.2) in in ASP.NET Core.

Thanks!

**Comment by joacoleza** [comment]
I ended adding to my `GraphQLUserContext` which implements `IProvideClaimsPrincipal` a `HttpContext` property. This property is being set when constructing it on the `GraphQLUserContextBuilder`.

Then, when implementing my `IAuthorizationRequirement` on the `Authorize` I can access the registered serv ice from the `HttpContext` doing:

```
HttpContext httpContext = ((GraphQLUserContext)context.UserContext).HttpContext;
var myService = (IMyService)httpContext.RequestServices.GetService(typeof(IMyService));
```

Is there a better way of doing so?

**Comment by joemcbride** [comment]
Here's an alternative way to do it:

```csharp
public class MyReq : IAuthorizationRequirement
{
    private readonly IHttpContextAccessor accessor;

    public MyReq(IHttpContextAccessor accessor)
    {
        this.accessor = accessor;
    }

    public Task Authorize(AuthorizationContext context)
    {
        return Task.CompletedTask;
    }
}

public static class GraphQLAuthExtensions
{
    public static void AddGraphQLAuth(this IServiceCollection services, Action<AuthorizationSettings, IServiceProvider> configure)
    {
        services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        services.TryAddSingleton<IAuthorizationEvaluator, AuthorizationEvaluator>();
        services.AddTransient<IValidationRule, AuthorizationValidationRule>();
        services.AddTransient<MyReq>();

        services.TryAddTransient(s =>
        {
            var authSettings = new AuthorizationSettings();
            configure(authSettings, s);
            return authSettings;
        });
    }
}

public void ConfigureServices(IServiceCollection services)
{
    services.AddGraphQLAuth((_, s) =>
    {
        _.AddPolicy("SomePolicy", p => p.AddRequirement(s.GetService<MyReq>()));
    });
}
```

**Comment by sungam3r** [comment]
Instead of 
```c#
   services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```
you can use special method
```c#
  services.AddHttpContextAccessor();
```
from **Microsoft.AspNetCore.Http** what does exacly the same thing.

**Comment by joemcbride** [comment]
I updated `IAuthorizationEvaluator` in the example to be registered as Transient.  Otherwise `AuthorizationSettings` would become a singleton indirectly.

**Comment by sungam3r** [comment]
Enabling scope validation on DI-container may help to find such problems.

**Comment by joacoleza** [comment]
> Here's an alternative way to do it:
> 
> ```cs
> public class MyReq : IAuthorizationRequirement
> {
>     private readonly IHttpContextAccessor accessor;
> 
>     public MyReq(IHttpContextAccessor accessor)
>     {
>         this.accessor = accessor;
>     }
> 
>     public Task Authorize(AuthorizationContext context)
>     {
>         return Task.CompletedTask;
>     }
> }
> 
> public static class GraphQLAuthExtensions
> {
>     public static void AddGraphQLAuth(this IServiceCollection services, Action<AuthorizationSettings, IServiceProvider> configure)
>     {
>         services.AddHttpContextAccessor();
>         services.AddTransient<IAuthorizationEvaluator, AuthorizationEvaluator>();
>         services.AddTransient<IValidationRule, AuthorizationValidationRule>();
>         services.AddTransient<MyReq>();
> 
>         services.TryAddTransient(s =>
>         {
>             var authSettings = new AuthorizationSettings();
>             configure(authSettings, s);
>             return authSettings;
>         });
>     }
> }
> 
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddGraphQLAuth((_, s) =>
>     {
>         _.AddPolicy("SomePolicy", p => p.AddRequirement(s.GetService<MyReq>()));
>     });
> }
> ```

Thanks! I'll do it this way

**Comment by mmmikeal** [comment]
this is incredibly helpful @joacoleza , do you have an example of how you added the service you want injected to the httpcontext and how you retrieve it out of the httpcontext? i am getting some type errors

**Comment by mmmikeal** [comment]
for example in my AddGraphQLAuth i have 

`services.AddHttpContextAccessor();
 services.AddTransient<MyServiceToBeInjected>();`

and in my requirement i attempt to access it by 
var service = `accessor.HttpContext.RequestServices.GetService<MyServiceToBeInjected>();`

**Comment by joacoleza** [comment]
> this is incredibly helpful @joacoleza , do you have an example of how you added the service you want injected to the httpcontext and how you retrieve it out of the httpcontext? i am getting some type errors

I no longer have access to the code where this was implemented. Sorry I couldn’t be more help.
