### ISSUE TITLE
AuthorizationEvaluator should check authentication state

### ISSUE THREAD

**Issue by Vouzamo** [graphql-dotnet/authorization#56]
The first thing in the default AuthorizationEvaluator .Evaluate method should be a check of principal.Identity.IsAuthenticated to conditionally return an AuthenticationResult.Fail() if false since claims are only valid for an authenticated user.

**Comment by Vouzamo** [comment]
Also seems odd that AuthorizeWith() and RequireAuthorization() extensions methods don't do any authorization checks by calling the internal Authorization evaluator and only check for claim matches.

**Comment by joemcbride** [comment]
The “next” branch adds an Authorization requirement that you can use to check for an authenticated user.  You can add that requirement today in your own codebase if you wish.

https://github.com/graphql-dotnet/authorization/commit/5795fb5acd8bf9c7537dc1b6eb85718dddffe789

**Comment by Vouzamo** [comment]
Ahhhh...

.RequireAuthorization() is not to mark a type as requiring authorization. It is a convenience method for checking if any policies have been defined against the type using the .RequireWith() method.

As such there is no method currently for flagging a type needs to be authorized but not against specific policies, correct?

I guess the requirement you suggest would still need to be registered against a policy and that policy used e.g. .RequireWith("authenticated");

**Comment by joemcbride** [comment]
Yes.  A policy could be anything, not only related to the authenticated user.  Such as, maybe your policy checks a configuration value or something like that.

**Comment by OpenSpacesAndPlaces** [comment]
See https://github.com/graphql-dotnet/authorization/issues/49#issuecomment-512007347
for an example flow.

Once you get used to the setup, it's actually pretty straight forward.

**Comment by sungam3r** [comment]
@Vouzamo Is this issue still actual?

**Comment by sungam3r** [comment]
Closed due to inactivity.
