### ISSUE TITLE
Unable to access Principle using GraphQL.Server 3.5

### ISSUE THREAD

**Issue by mehtanilay10** [graphql-dotnet/authorization#64]
I have used GraphQL.Server.Transports.AspNetCore **v3.5**.
In which there is change in `AddUserContextBuilder()`.
Now TUserContext will be `IDictionary<string, object>` instead of IProvideClaimsPrincipal.
So here need to update AuthorizationValidationRule for aligning it with the Server package.

Here is its Ref: https://github.com/graphql-dotnet/server/pull/218

**Comment by sungam3r** [comment]
@mehtanilay10 In fact, everything is not so bad. `IProvideClaimsPrincipal` must stay. Just use this approach:

```c#
  class GraphQLUserContext : Dictionary<string, object>, IProvideClaimsPrincipal
    {
        public ClaimsPrincipal User { get; set; }
    }
```
A user context can easily combine implementations of both interfaces.

**Comment by mehtanilay10** [comment]
Okay, It works prety good. Thanks @sungam3r
