### ISSUE TITLE
FieldBuilder AuthorizeWith not consistent with IProvideMetadata AuthorizeWith

### ISSUE THREAD

**Issue by BillBaird** [graphql-dotnet/authorization#66]
In the AuthorizationMetadataExtensions class, the IProvideMetadata AuthorizeWith extension allows a list of policies; however, the corresponding FieldBuilder AuthorizeWith extension method only allows for a single policy.  I believe these should behave identically, each allowing for multiple policies (which all must be true).  

I suggest changing:

```
        public static FieldBuilder<TSourceType, TReturnType> AuthorizeWith<TSourceType, TReturnType>(
            this FieldBuilder<TSourceType, TReturnType> builder, string policy)
        {
            builder.FieldType.AuthorizeWith(policy);
            return builder;
        }
```
to

```
        public static FieldBuilder<TSourceType, TReturnType> AuthorizeWith<TSourceType, TReturnType>(
            this FieldBuilder<TSourceType, TReturnType> builder, params string[] policies)
        {
            builder.FieldType.AuthorizeWith(policies);
            return builder;
        }
```

**Comment by sungam3r** [comment]
Or allow to **append** policy inside `AuthorizeWith`.

**Comment by BillBaird** [comment]
Either way (multiple policies, or append), they should be consistent.  I can create a PR for this and the corresponding tests if desired.

**Comment by sungam3r** [comment]
@BillBaird Code with extension methods was [moved](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/AuthorizationExtensions.cs) into main GraphQL.NET repo.

> Either way (multiple policies, or append), they should be consistent.

Append approach won.
