### ISSUE TITLE
How do I use Authorization with ConnectionBuilder ?

### ISSUE THREAD

**Issue by alonstar** [graphql-dotnet/authorization#67]
I need pagination, so I used [Relay](https://github.com/graphql-dotnet/relay) to implement. But how do I use AuthorizeWith on Connection Field ?

**Comment by photomoose** [comment]
There's an extension method in the latest GraphQL.Server.Authorization.AspNetCore package from the MyGet feed (3.5.0-alpha0069):

```
            Connection<SubscriptionType>()
                .Name("subscriptions")
                .AuthorizeWith("AuthenticatedUser")
```

**Comment by sungam3r** [comment]
Closed as resolved.
