### ISSUE TITLE
Not compatible with graphql-dotnet 3.0

### ISSUE THREAD

**Issue by withinboredom** [graphql-dotnet/authorization#71]
In the latest of [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet/blob/43a80a883997a88f9dd9e22d3ca2f80b6183825f/src/GraphQL.Harness/GraphQLSettings.cs) `UserContext` is expected to be a `Dictionary<string, object>` and not an `object`.

This could probably be handled by adding [a simple bit](https://github.com/graphql-dotnet/authorization/blob/master/src/GraphQL.Authorization/AuthorizationValidationRule.cs#L20):

```csharp
// var userContext = context.UserContext as IProvideClaimsPrincipal;
IProvideClaimsPrinciple userContext;
if(context.UserContext is Dictionary<string, object>) {
  userContext = (context.UserContext as Dictionary<string, object>)?["user"] as IProvideClaimsPrinciple;
} else {
  userContext = context.UserContext as IProvideClaimsPrinciple;
}
```

**Comment by sungam3r** [comment]
Can you explain the problem in more detail?

**Comment by withinboredom** [comment]
Sure, the `ValidationContext` implements (`IProvideUserContext`)[https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/IProvideUserContext.cs] which an `IDictionary` and not an Object (like it was in earlier versions). This means, in the very least, that either:

1. `GraphQLUserContext` needs to also implement `IDictionary<string, object>`
1. or, `GraphQLUserContext` needs to check a "well-known" key for the principle.

As it stands right now, it doesn't work at all unless (1) is implemented because [`ExecutionOptions`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionOptions.cs#L31) only accepts an `IDictionary<string, object>`

**Comment by sungam3r** [comment]
> the ValidationContext implements IProvideUserContext which an IDictionary and not an Object 

This is the expected behavior. https://github.com/graphql-dotnet/authorization/blob/master/src/Harness/GraphQL.cs#L8 , examples have been modified accordingly.

Do you have a runtime errors?

**Comment by withinboredom** [comment]
Oh, nice I missed that! Closing this :)
