### ISSUE TITLE
Preview Targeting

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/authorization#75]
3.0.39-preview-39 is targeting 3.0.0-preview-1352 instead of 3.0.0-preview-1648.

I'm not able to binding redirect without a public token - is there another work around?

**Comment by joemcbride** [comment]
@OpenSpacesAndPlaces I pushed `GraphQL.Authorization - 3.0.40-preview-40` to Nuget, targeting `3.0.0-preview-1648.`.  Let me know if you run into any issues.  I still have work to do to upgrade our manual test harness, but all of the existing tests are passing.
