### ISSUE TITLE
Tag 2.1.29 Release?

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/authorization#77]
Can you tag the 2.1.29 Release like you did here:
https://github.com/graphql-dotnet/graphql-dotnet/issues/1677

I checked here, but did not see it:
https://github.com/graphql-dotnet/authorization/tags

Thanks!!!

**Comment by OpenSpacesAndPlaces** [comment]
@joemcbride

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/authorization/releases/tag/v2.1.29

**Comment by joemcbride** [comment]
I bumped the `v2.1.29` tag to https://github.com/graphql-dotnet/authorization/commit/bc3b36ed1885236f36bc8db4dded8fd032d2ce58, confirmed from this build: https://ci.appveyor.com/project/graphql-dotnet-ci/authorization/builds/21728911

**Comment by sungam3r** [comment]
That is, I set it to the correct commit?

**Comment by joemcbride** [comment]
@sungam3r It looked like you set it to `2.1.31` build vs. `2.1.29`.

https://github.com/graphql-dotnet/authorization/commit/48ee6f623a08ecc5c02c80a7ca8aeaf1e18046c7

Would be nice to get this automated in Github Actions (something I need to look at closer).
https://ci.appveyor.com/project/graphql-dotnet-ci/authorization/builds/24380676

**Comment by sungam3r** [comment]
I set this one
![изображение](https://user-images.githubusercontent.com/21261007/82377152-f00ee280-9a2b-11ea-8c2b-c5da9154ce20.png)

**Comment by OpenSpacesAndPlaces** [comment]
Thanks!
