### ISSUE TITLE
Faulty reference

### ISSUE THREAD

**Issue by Blanen** [graphql-dotnet/authorization#81]
![image](https://user-images.githubusercontent.com/7236824/93207009-9492fe00-f75a-11ea-9138-86ff84f0cac0.png) 

This isn't a published version on nuget as far as I know.

This happens after installing GraphQL.Authorization 3.0.43 (there is no 3.0.0) . Only 3.0.0 is available of the GraphQL package.

**Comment by Blanen** [comment]
https://github.com/graphql-dotnet/authorization/pull/80 similar.

But even trying to get it via myget 

![image](https://user-images.githubusercontent.com/7236824/93208559-0cfabe80-f75d-11ea-9ea7-918d6528d818.png)

**Comment by Blanen** [comment]
@joemcbride Since you seem to have committed 3.0.0

**Comment by Blanen** [comment]
I got it working via an assembly ref but that's obviously not desired.

**Comment by Blanen** [comment]
Probably PEBCAK

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/GraphQL.Authorization/3.0.43

 Dependencies

    .NETStandard 2.0
        GraphQL (>= 3.0.0)

**Comment by sungam3r** [comment]
Closing this issue. Feel free to ask further questions if any.
