### ISSUE TITLE
How to login user and return token and id ?

### ISSUE THREAD

**Issue by AAIING** [graphql-dotnet/authorization#83]
i dont know apply return id and token to try login user

Login resolver

```c#
    public class LoginAuth : ObjectGraphType
    {
        private readonly DataContext _context;
        private readonly IConfiguration _configuration;
       
        public LoginAuth(DataContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;

            Field<LoginType>(
             "login",
             arguments: new QueryArguments(
                 new QueryArgument<NonNullGraphType<LoginInputType>> { Name = "login" }
             ),
             resolve: context =>
             {
                                 
                 LoginModel login = context.GetArgument<LoginModel>("login");
   
                 var usuariodb = _context.Usuarios.SingleOrDefault(x => x.Email == login.Email && x.Contrasena == login.Contrasena);
    
                 if (usuariodb == null)
                 {
                     context.Errors.Add(new ExecutionError("usuario o contraseña incorrecta"));
                     return null;
                 }
             
                 //return usuariodb;
                 var tokenUser = CreateToken(usuariodb);
 
                 return usuariodb; 

             });

        }
```

**Comment by sungam3r** [comment]
Please specify what question you have.

**Comment by AAIING** [comment]
> Please specify what question you have.

Hi Ivan, my question is how to trying a mutation login (username and password) and in the response query only show the token and  id_user. you understand? 

error:
![image](https://user-images.githubusercontent.com/46494254/97358330-e2cb0f00-1879-11eb-91db-9a36a0df39be.png)

Error: "(eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJwZXBpdG9AcGVyZXouY2wiLCJuYmYiOjE2MDM4MzA1MTYsImV4cCI6MTYwMzkxNjkxNiwiaWF0IjoxNjAzODMwNTE2fQ.mQ9IV8iL-IBG8SIaWD69uFBnpgA0bK35tE-ppP4f6q6eDtEUJKpL8ICXb7XrYYxOBD2WRBrP9yjl9e_uRW00xg, WebAppEF1.Models.Usuario)" value of type "System.ValueTuple`2[System.String,WebAppEF1.Models.Usuario]" is not allowed for "LoginType". Either change IsTypeOf method of "LoginType" to accept this value or return another value from your resolver.

i buy a coffe for you!!

**Comment by sungam3r** [comment]
You return object of type `System.ValueTuple2[System.String,WebAppEF1.Models.Usuario]` from resolver for field "login" but that field has type `LoginType` which is not compatible with returned object. The error message is quite verbose. This check happend inside `protected virtual void ValidateNodeResult(ExecutionContext context, ExecutionNode node)`:
```c#
if (objectType?.IsTypeOf != null && !objectType.IsTypeOf(result))
{
     throw new InvalidOperationException($"\"{result}\" value of type \"{result.GetType()}\" is not allowed for \"{objectType.Name}\". Either change IsTypeOf method of \"{objectType.Name}\" to accept this value or return another value from your resolver.");
}
```

Please provide definition of `LoginType` to investigate further.

**Comment by Ekkeir** [comment]
I'm not nearly @sungam3r, but as of now you're returning usuariodb value, which seems to be an instance of `System.String,WebAppEF1.Models.Usuario` while your intention is seemingly to return the token and IdUser

Assuming that `LoginType` is defined something like the following
```c#
class LoginType : ObjectGraphType<Login>
{
    public LoginType()
    {
        Field(x => x.Token);
        Field(x => x.IdUser);
    } 
}
```

and `Login` is defined something like this
```c#
class Login
{
    public string Token;
    public string IdUser;
}
```

then you'd have to combine it all in your resolver like this presumably
```c#
public class LoginAuth : ObjectGraphType
    {
        ...

        public LoginAuth(DataContext context, IConfiguration configuration)
        {
             ...             
             resolve: context =>
             {
                                 
                 ....
   
                 var usuariodb = _context.Usuarios.SingleOrDefault(x => x.Email == login.Email && x.Contrasena == login.Contrasena);
    
                 ...
             
                 var tokenUser = CreateToken(usuariodb);
 
                 // the only changed part here
                 return new Login { Token = tokenUser, IdUser = usuariodb.IdUser };
             });

        }
```

It is not precise, but should be somewhere close.

P.S. and your mutation would look approximately like this, I think
`
mutation($login: LoginInput!)
{
    login(login: $login) { IdUser login }
}
`
